"""removed time from tip object

Revision ID: 495bfc1cf517
Revises: e2f30a59278d
Create Date: 2023-10-20 18:59:47.563623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '495bfc1cf517'
down_revision = 'e2f30a59278d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tips', schema=None) as batch_op:
        batch_op.drop_column('tip_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tip_time', sa.TIME(), nullable=True))

    # ### end Alembic commands ###
