"""imgur delete hash

Revision ID: d1e465326f9d
Revises: 01a8f9135716
Create Date: 2023-10-07 18:02:37.607659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1e465326f9d'
down_revision = '01a8f9135716'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imgur_delete_hash', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('imgur_delete_hash')

    # ### end Alembic commands ###
