"""added tip models

Revision ID: e8c669271662
Revises: d1e465326f9d
Create Date: 2023-10-18 22:49:24.235653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8c669271662'
down_revision = 'd1e465326f9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tip_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.String(), nullable=True),
    sa.Column('day_night', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('average_tip', sa.Float(), nullable=True),
    sa.Column('num_tips', sa.Integer(), nullable=True),
    sa.Column('restaurant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name=op.f('fk_tip_statistics_restaurant_id_restaurants')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('tip_date', sa.Date(), nullable=True),
    sa.Column('tip_time', sa.Time(), nullable=True),
    sa.Column('day_night', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tips_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tips')
    op.drop_table('tip_statistics')
    # ### end Alembic commands ###
